export const CustomColors = {
  backgroundColor: '#f5f5f5',
  primaryColor: '#af2eff',
  primaryColorDark: '#24003b',
  primaryColorLight1: '#bd57ff',
  primaryColorLight2: '#d9a1ff',
  secondaryColor: '#ff21bc',
  accentColor: '#FFA500',
  accentColorLight: '#fff3de',
  accentColorDark: '#c27e00',
  white: '#fff',
  black: '#000',
  offWhite: '#fafafa',
  whiteShade1: '#ededed',
  whiteShade2: '#e3e3e3',
  whiteShade3: '#cccccc',
  transparent: '#FFFFFF',
  darkAccent: '#1f1400',
  lightBlack: '#4d4d4d',
  warningColor: '#D65352',
};
