export const ADD_PLACE = 'ADD_PLACE';
export const CLEAR_DATA = 'CLEAR_DATA';
export const GET_USER_FETCH = 'GET_USER_FETCH';
export const GET_USER_FETCH_SUCCESS = 'GET_USER_FETCH_SUCCESS';
export const SET_DARK_MODE = 'SET_DARK_MODE';
export const SET_CURRENT_DRAWER_SCREEN = 'SET_CURRENT_DRAWER_SCREEN';
export const SET_CURRENT_COMPANY_INDEX = 'SET_CURRENT_COMPANY_INDEX';
